### ISSUE TITLE
Corals doesn't drop on breaking

### ISSUE THREAD

**Issue by craft90** [Cuplex17/Deep-Sea-Salvage#1]
I have noticed that when you break coral it doesn't drop. However if you break the bottom coral of a two blocks+ coral, do do get one item. I haven't tested this but I have a feeling that maybe whatever mod there is that replaces flowing water blocks with source blocks possibly in doing so also deletes whatever item lays there, Possibly due to how (I assume BetterWithAddons) forces the items to lay flat on ground rather than the vanilla way. Supposedly, this is just an idea, perhaps the 3D items counts as a block, thereby getting removed together with flowing water. This issue wasn't in the previous version so some new config or mod caused this.

Another idea I have is that it could be due to TidyChunk killing item entities to lower lag. However I don't know how that would happen. I can't see any config nor black list.

Speaking of corals, I know you can sieve them now through sand. But the sieve can't be made in the basic crafting bench. It can be made in the Workstump however, the Workstump has a 3x3 shaped recipe which can't be made in neither the 2x2 player grid, nor the basic crafting bench.

**Comment by Cuplex17** [comment]
Thank you for reporting this. I'll look into this and put out a fix as soon as I can. 

Edit: the water source replacing this is a custom crafttweaker script I wrote. It works with most of the other things. I'll try TidyChunk and see if that's the problem. Originally intended it to remove world gen lag. The crafting issues are already known, I forgot to add them in with the previous update.

**Comment by Cuplex17** [comment]
Fixed in v0.1.1
