### ISSUE TITLE
[CriticalBug] Ores doesn't drop on mining.

### ISSUE THREAD

**Issue by craft90** [Cuplex17/Deep-Sea-Salvage#2]
I mines iron ore with an iron pick. I didn't get the ore. It just went poof and then it was gone.

**Comment by craft90** [comment]
Btw I was mining this under water. Mining in air doesn't make the item go poof. This is a pretty much game breaking bug. If I would guess then it could be because of how air nearby water get replaced with source block water (even if it's above the water...). Perhaps it conflicts with the 3D rendering of Realistic Drops.

**Comment by Cuplex17** [comment]
It seems I need to do more testing, thanks again for submiting all these bugs.

**Comment by Cuplex17** [comment]
I found the bug. It's in my custom scripts where it deletes the block before it replaces it with water, so the block doesn't drop anything. I'll try to implement a fix for it, if not, I'll just remove it.

**Comment by Cuplex17** [comment]
Fixed in v0.1.1
