### ISSUE TITLE
0.1.1 Better Quest book blank

### ISSUE THREAD

**Issue by blankenstein** [Cuplex17/Deep-Sea-Salvage#4]
Fresh install from twitch App

Opening the quest book shows a blank panel on a blank book.

Quests appear to be in the BQ database but no quest lines are defined.

**Comment by Cuplex17** [comment]
I have not added any quests yet. I want to get the main progression line sorted out before I do any quests. Just in case I change my mind half way through and having to delete all the quests to start over.
